<a href="https://www.kaggle.com/code/rohit4468/linear-regression-polynomial-regression?scriptVersionId=308168585" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        pass
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/nalisha/job-salary-prediction-dataset/job_salary_prediction_dataset.csv
/kaggle/input/datasets/shahpranshu27/placement-dataset-updated-2024/updated_placement.csv

# Librarires

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# Simple Linear Regresssion

In [3]:
#Y=mx+c

In [4]:
class LR:
    def __init__(self):
        self.m=None
        self.c=None

    def fit(self, X_train, y_train):

        num=0
        den=0
        for i in range(len(X_train)):
            num=num+(X_train.iloc[i]-X_train.mean())*(y_train.iloc[i]-y_train.mean())
            den=den+(X_train.iloc[i]-X_train.mean())*(X_train.iloc[i]-X_train.mean())


        self.m=num/den
        self.c=y_train.mean()-self.m*X_train.mean()


    def predict(self, X_test):

        return self.m*X_test + self.c

## DataFrame

In [3]:
df=pd.read_csv('/kaggle/input/datasets/shahpranshu27/placement-dataset-updated-2024/updated_placement.csv')
df.head(5)

   cgpa    package
0  9.75  68.493428
1  5.36  23.323471
2  5.65  27.795377
3  5.60  29.046060
4  6.48  34.331693

## Train Test Split

In [4]:
X=df.iloc[:,:1]
y=df.iloc[:,-1]

In [5]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=42)
X_train.shape, y_train.shape

((160, 1), (160,))

## Model Train

In [8]:
lr=LR()
lr.fit(X_train, y_train)

In [9]:
y_pred=lr.predict(X_test)

## Predifined model

In [10]:
lr_predifined=LinearRegression()
lr_predifined.fit(X_train, y_train)
y_pred_predifined=lr_predifined.predict(X_test)

## Error Compare

In [11]:
#custom 
r2_e=r2_score(y_test, y_pred)
mse_e=mean_squared_error(y_test, y_pred)
mae_e=mean_absolute_error(y_test, y_pred)

r2_e, mse_e, mae_e

(0.8196164361684541, 37.81026595182169, 3.076592045660713)

In [12]:
#predifined
r2_e_predifined=r2_score(y_test, y_pred_predifined)
mse_e_predifined=mean_squared_error(y_test, y_pred_predifined)
mae_e_predifined=mean_absolute_error(y_test, y_pred_predifined)

r2_e_predifined, mse_e_predifined, mae_e_predifined

(0.8196164361684539, 37.81026595182173, 3.076592045660715)

In [13]:
#diffrence between error
r2_e-r2_e_predifined, mse_e-mse_e_predifined, mae_e-mae_e_predifined

(2.220446049250313e-16, -3.552713678800501e-14, -1.7763568394002505e-15)

# Multiple Linear Regression

In [14]:
class MLR:
    def __init__(self):
        self.coef=None
        self.intercept=None

    def fit(self, X_train, y_train):
        X_train=np.insert(X_train, 0, 1, axis=1)
        betas=np.linalg.pinv(X_train.T @X_train) @X_train.T @ y_train

        self.intercept=betas[0]
        self.coef=betas[1:]

    def predict(self, X_test):
        y_pred =np.dot(X_test, self.coef) + self.intercept

        return y_pred

## DataFrame

In [11]:
df=pd.read_csv('/kaggle/input/datasets/nalisha/job-salary-prediction-dataset/job_salary_prediction_dataset.csv')
df.head(5)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

### preprocessing : OHE

In [16]:
from sklearn.preprocessing import OneHotEncoder
ohe_features = ['job_title','education_level','industry','company_size','location','remote_work']

ohe = OneHotEncoder(sparse_output=False)

encoded = ohe.fit_transform(df[ohe_features])

encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(ohe_features),
    index=df.index
)

encoded_df

,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
249996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
249997,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
249998,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
249999,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [17]:
df_num=df[['experience_years','skills_count','certifications','salary']]
df=pd.concat((encoded_df,df_num), axis=1)
df.head()

,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,...,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes,experience_years,skills_count,certifications,salary
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,10,2,2,109413
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,5,17,0,93764
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,18,4,1,148123
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,19,13,0,189123
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,15,7,0,165069

In [18]:
df.shape

(250000, 49)

## train test split

In [19]:
X=df.iloc[:,:33]
y=df.iloc[:,-1]

In [20]:
X_train, X_test,  y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=42)
X_train.shape, y_train.shape

((200000, 33), (200000,))

# model selection

In [21]:

lr=MLR()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)

In [22]:
#predifined model
from sklearn.linear_model import LinearRegression

lr_p=LinearRegression()
lr_p.fit(X_train, y_train)
y_pred_p=lr_p.predict(X_test)

## Model Evaluation`

In [23]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

#custom 
r2_e=r2_score(y_test, y_pred)
mse_e=mean_squared_error(y_test, y_pred)
mae_e=mean_absolute_error(y_test, y_pred)

r2_e, mse_e, mae_e

(0.4219989093036456, 803342696.285233, 22276.29826271468)

In [24]:
#predifined
r2_e_predifined=r2_score(y_test, y_pred_p)
mse_e_predifined=mean_squared_error(y_test, y_pred_p)
mae_e_predifined=mean_absolute_error(y_test, y_pred_p)

r2_e_predifined, mse_e_predifined, mae_e_predifined

(0.42193158911350026, 803436262.16934, 22276.18382)

# Polynomial linear regression

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
poly=PolynomialFeatures(degree=4)
x_poly=poly.fit_transform(X_train)
lr=LinearRegression()
lr.fit(x_poly, y_train)

LinearRegression()

In [10]:
x_test_poly=PolynomialFeatures(degree=4)
x_test_poly=x_test_poly.fit_transform(X_test)

#prediction
y_pred=lr.predict(x_test_poly)

#evation
r2_e=r2_score(y_test, y_pred)
mse_e=mean_squared_error(y_test, y_pred)
mae_e=mean_absolute_error(y_test, y_pred)

r2_e, mse_e, mae_e

(0.8191429593376074, 37.909511606559164, 3.0384388239993947)